---
- name: set up local environment
  hosts: local

  vars:
    user_home: "{{ '~' | expanduser }}"
    bootstrap_home: "{{ user_home }}/.bootstrap"
    dotfiles_home: "{{ user_home }}/.dotfiles"

  roles:
    - { role: base, tags: ["bootstrap"] }
    - { role: dev, tags: ["dev"] }
    - { role: user-settings, tags: ["always"] }
