---
- name: install .dotfiles
  git:
    repo: "{{ dotfiles_repository }}"
    dest: "{{ dotfiles_home }}"
    update: no
    accept_hostkey: true

- name: run gnu stow
  command: stow -d {{ dotfiles_home }} -t {{ user_home }} git hg misc ssh vim zsh

- name: run set-user-defaults.sh
  script: "{{ dotfiles_home }}/macos/set-user-defaults.sh"
  when: ansible_os_family == "Darwin"
  changed_when: false

- name: run chsh -s /usr/bin/zsh {{ ansible_user }}
  command: chsh -s /usr/bin/zsh {{ ansible_user }}
  when: ansible_os_family == "Debian"
  changed_when: false
  become: yes

- name: run chsh -s /usr/local/bin/zsh
  command: chsh -s /usr/local/bin/zsh
  when: ansible_os_family == "Darwin"

- name: skipping ssh-agent default key
  lineinfile:
    path: "{{ user_home }}/.zshrc"
    regexp: 'zstyle :omz:plugins:ssh-agent identities pmyszka'
    state: absent
  when: ansible_os_family == "Debian"

- name: changing antigen settings for Debian
  lineinfile:
    path: "{{ user_home }}/.zshrc"
    regexp: 'source /usr/local/share/antigen/antigen.zsh'
    line: 'source /usr/share/zsh-antigen/antigen.zsh'
  when: ansible_os_family == "Debian"
