---
- name: install macos_cask_packages_dev
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ macos_cask_packages_dev }}"
  when: ansible_os_family == "Darwin"

- include_tasks: java.yml
- include_tasks: clojure.yml

